Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2023-12, with the labels that each got.

#41 [BE-20] feat: SecurityUtils 기능 추가 #34
  .github/workflows/CI_Check.yml
  .gitignore
  README.md
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/service/CouponWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityUtils.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleRequestDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleResponseDto.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/test/java/com/jnu/ticketapi/TicketApiApplicationTests.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/LoginTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/supports/ApiIntegrateProfileResolver.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/supports/ApiIntegrateSpringBootTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/supports/ApiIntegrateTestConfig.java
  Ticket-Common/src/test/java/com/jnu/ticketcommon/TicketCommonApplicationTests.java
  Ticket-Domain/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/System.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/SystemRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/out/UserLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/persistence/UserPersistenceAdapter.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/TicketDomainApplicationTests.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAopTest.java
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedissonConfig.java
  Ticket-Infrastructure/src/main/resources/application-infrastructure.yml
  Ticket-Infrastructure/src/main/resources/application.yml
  Ticket-Infrastructure/src/test/java/com/jnu/ticketinfrastructure/InfraIntegrateProfileResolver.java
  Ticket-Infrastructure/src/test/java/com/jnu/ticketinfrastructure/InfraIntegrateSpringBootTest.java
  Ticket-Infrastructure/src/test/java/com/jnu/ticketinfrastructure/InfraIntegrateTestConfig.java
  Ticket-Infrastructure/src/test/java/com/jnu/ticketinfrastructure/TicketInfrastructureApplicationTests.java
  build.gradle
Labels: 기능

#46 Hotfix 24
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityUtils.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
Labels: 버그, 뜨거운 감자

#48 [BE-25] bug: 임시저장/1차신청
  .gitignore
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationService.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/RegistrationUseCase.java
  Ticket-Domain/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
Labels: 버그

#49 [BE-23] feature: 권한 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/UpdateRoleRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdateRoleResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UserUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/UserUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/service/AuthService.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/service/UserService.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/controller/UserController.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserRecordPort.java
  Ticket-Domain/src/main/resources/application-domain.yml
Labels: 기능

#53 [BE-27] hotfix: cors, options 403에러
  Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
Labels: 뜨거운 감자

#51 [BE-18] feature: 공지사항 CRUD
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/controller/AnnounceController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/SaveAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/UpdateAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceDetailsResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceInfoResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnouncePagingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/DeleteAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/SaveAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/UpdateAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/DeleteAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/GetAnnouncesUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/SaveAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceIdNotExistException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceNotExistException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/TicketDomainApplication.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/domain/Announce.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/repository/AnnounceRepository.java
Labels: 기능

#55 [BE-27] hotfix: CORS 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
Labels: 뜨거운 감자

#56 [BE-27] : hotfix: SecurityConfig 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Labels: 뜨거운 감자

#57 [BE-27] hotfix: 빌드 안되는 것 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/controller/AnnounceController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/SaveAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/UpdateAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceDetailsResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceInfoResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnouncePagingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/DeleteAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/SaveAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/UpdateAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/DeleteAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/GetAnnouncesUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/SaveAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceIdNotExistException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/AnnounceNotExistException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/domain/Announce.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/out/AnnounceRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/repository/AnnounceRepository.java
Labels: 뜨거운 감자

#59 [BE-27] hotfix : SecurityConfig 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Labels: 뜨거운 감자

#58 [BE-28] feat: 안내사항 수정, 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/controller/NoticeController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/request/UpdateNoticeRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/NoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/UpdateNoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/GetNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/UpdateNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseCleaner.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseClearExtension.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/GetNoticeTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/UpdateNoticeTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NoticeNotExistException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/adaptor/NoticeAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/domain/Notice.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/repository/NoticeRepository.java
Labels: 기능, 버그

#60 [BE-27] hotfix : SecurityConfig 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Labels: 뜨거운 감자

#65 [BE-29] docs: 공지사항, 안내사항 기능 Swagger 예외 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/controller/AnnounceController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/DeleteAnnounceExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/GetAnnounceExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/docs/UpdateAnnounceExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/controller/NoticeController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/docs/GetNoticeExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/request/UpdateNoticeRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/NoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/UpdateNoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/GetNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/UpdateNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseCleaner.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/config/DatabaseClearExtension.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/GetNoticeTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/UpdateNoticeTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NoticeNotExistException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/announce/adaptor/AnnounceAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/adaptor/NoticeAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/domain/Notice.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/out/NoticeRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/notice/repository/NoticeRepository.java
Labels: 리팩터링, 문서화

#61 [BE-21] feat: 대기열 순위 조회 API #39
  Ticket-Api/build.gradle
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/controller/CouponController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/docs/ReadCouponExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/handler/CouponIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/model/request/WaitingQueueRequestDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/service/CouponRegisterUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/service/CouponWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationService.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/response/SuccessResponseAdvice.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/security/CustomUserDetails.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/utils/Result.java
  Ticket-Domain/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLock.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAop.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/adaptor/CouponAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/domain/Coupon.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/out/SectorRecordPort.java
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAopTest.java
  Ticket-Infrastructure/build.gradle
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/CouponIssuedEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/Events.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/InfrastructureEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/RedisEventPublisherAspect.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponIssueService.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponSubscribeService.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 기능

#67 [Hotfix] refactor: 배포 서버의 hibernate ddl-auto을 임시로 create-drop 으로 설정
  Ticket-Domain/src/main/resources/application-domain.yml
Labels: 뜨거운 감자

#78 [BE-27] 캡차 기능 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaPendingAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaPendingException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaAnswerException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaPendingRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
  Ticket-Domain/src/main/resources/application-domain.yml
Labels: 기능, 리팩터링

#69 [BE-26] feat: 학생회 로그인
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/internal/TokenDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginCouncilRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginUserRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/ReissueTokenRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/response/LoginCouncilResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/response/LoginUserResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/response/LogoutUserResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/response/ReissueTokenResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/model/request/CouponRegisterRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetRegistrationResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/internal/SectorDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/request/SectorRegisterRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/LoginUserResponseDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/LogoutUserResponseDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ReissueTokenRequestDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ReissueTokenResponseDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/security/JwtAuthenticationFilter.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/LoginTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/adaptor/CouncilAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/domain/Council.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
Labels: 기능

#70 [BE-32] feat: 학생회 회원가입
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/request/SignUpCouncilRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/response/SignUpCouncilResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaPendingAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaPendingException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaAnswerException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaPendingRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/adaptor/CouncilAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/domain/Council.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/repository/CouncilRepository.java
Labels: 기능

#75 [BE-33] refactor: GetRegistration에서 UserId 추출
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UserUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
Labels: 성능개선

#82 [BE-30] feat: 비밀번호 찾기 기능
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/FindPasswordRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/UpdatePasswordRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/FindPasswordResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdatePasswordResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/CredentialCodeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UpdatePasswordUseCase.java
  Ticket-Api/src/main/resources/templates/findPassword.html
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/FindPasswordTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/UpdatePasswordTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/MailTemplate.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/MailMessage.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/adaptor/CredentialCodeAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/domain/CredentialCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/out/CredentialCodeLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/out/CredentialCodeRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/repository/CredentialCodeRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/CredentialCodeNotExistException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/exception/UserErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserRecordPort.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/thymeleaf/ThymeleafConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
Labels: 기능, 리팩터링

#79 [BE-36] bug: 권한 설정을 하기 위한 학생회 회원가입 목록 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/internal/UserDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/request/UpdateRoleRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/GetUserListResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/UpdateRoleResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/request/SignUpCouncilRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/request/UpdateRoleRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdateRoleResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UserUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/adaptor/AdminAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/adaptor/CouncilAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/domain/Council.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/out/CouncilRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserRecordPort.java
Labels: 기능, 버그

#91 [BE-43] bug: 비밀번호 재발급 500 오류 트랜잭션 버그 픽스
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/adaptor/CredentialCodeAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/CredentialCode/repository/CredentialCodeRepository.java
Labels: 버그

#93 [BE-44] feat: 1차 신청 목록 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/GetUsersResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/internal/RegistrationDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetRegistrationsResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
Labels: 기능

#95 [BE-39] bug: 학생회 로그인
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/CouncilErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/IsNotCouncilException.java
Labels: 버그

#102 [BE - docs] SuccessResponse 긴급수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/controller/CouponController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/dto/SuccessResponse.java
Labels: 문서화

#104 [BE-40] bug : 임시저장 / 1차신청
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetCaptchaResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/DecryptionErrorException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/EncryptionErrorException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
Labels: 기능, 버그

#97 [BE-31] feat:주차권 신청 재고 감소 로직 정합성 개선 #66
  .gitignore
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/controller/CouponController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/handler/CouponIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/service/CouponWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/LoginTest.java
  Ticket-Domain/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/model/ChatMessage.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponIssueService.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponSubscribeService.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
  build.gradle
  intellij-java-google-style.xml
Labels: 기능, 성능개선

#111 [BE-51] feat: 예외케이스 Swagger 적용
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/controller/UserController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/docs/UpdatePasswordExceptionDocs.java
Labels: 리팩터링, 문서화

#113 [BE-48] docs: ErrorDocs 작성
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/docs/UpdateRoleExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/TokenReissueExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginUserRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/docs/GetCaptchaExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/docs/UpdatePasswordExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotEqualPrincipalException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotFoundRefreshTokenException.java
Labels: 문서화

#117 [BE-53] feat: 이벤트 주최 시간 조회 #115
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/controller/CouponController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/docs/ReadCouponExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/coupon/service/CouponWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/exception/CouponErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/coupon/exception/NotOpenCouponPeriodException.java
  intellij-java-google-style.xml
Labels: 기능, 문서화

#109 [BE-50] refactor: 부적절한 of, from 메서드 네이밍 변경
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/response/UpdateRoleResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceDetailsResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceInfoResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnouncePagingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/AnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/SaveAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/response/UpdateAnnounceResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/GetAnnouncesUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/SaveAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/service/UpdateAnnounceUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/NoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/model/response/UpdateNoticeResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/GetNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/notice/service/UpdateNoticeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/FinalSaveResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/TemporarySaveResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/model/response/UpdatePasswordResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/UpdatePasswordUseCase.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/CouponIssuedEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/CouponSubscribeService.java
Labels: 리팩터링

#121 [BE-57] refactor: 캡챠 도메인 리팩토링
  .gitignore
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/controller/CaptchaController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/docs/GetCaptchaExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaPendingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/model/response/CaptchaResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaPendingUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaPendingAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/Captcha.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaPending.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaPendingException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaPendingRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaPendingRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
Labels: 리팩터링, 성능개선, 뜨거운 감자

#133 [BE-63] bug: 토큰 재발급
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/common/aop/EmailMethodArgumentResolver.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
Labels: 버그

#135 [BE-64] feat: Event Time UTC Zone setting #134
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
Labels: 버그

#122 [Hotfix] chore: DB 스키마 업데이트 체크리스트 추가
  .github/ISSUE_TEMPLATE/기능구현.md
  .github/ISSUE_TEMPLATE/리팩터링.md
  .github/ISSUE_TEMPLATE/버그수정.md
Labels: 문서화, 뜨거운 감자

#138 [BE-65] feat: 프론트 도메인 CORS 설정 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Labels: 기능

#139 [Hotfix] : Cors 설정 핫픽스
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
Labels: 리팩터링, 뜨거운 감자, 프로젝트 설정

#140 [Hotfix] : Cors 설정 핫픽스 2
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
Labels: 뜨거운 감자, 프로젝트 설정

#141 [Hotfix] : Cors 설정 핫픽스 3
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
Labels: 뜨거운 감자

#143 [BE-66] feat: Phone, Password Validator 미작동 이슈 해결 #142
  Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/SecurityConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Phone.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/validator/PhoneValidator.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
Labels: 버그

#146 [BE-68] bug : 1차 신청 목록 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 버그, 뜨거운 감자

#147 [BE-67] feat: 학생 상태(합격자, 예비자...) 변경 #144
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
Labels: 기능, 리팩터링, 성능개선

#150 [BE-56] test : 통합 테스트
  Ticket-Api/build.gradle
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/controller/AdminController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/model/request/UpdateRoleRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/TokenReissueExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/CheckEmailRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginCouncilRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/LoginUserRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/ReissueTokenRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/request/SignUpCouncilRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/response/GlobalExceptionHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/security/JwtResolver.java
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/DeleteAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/GetAnnouncesTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/SaveAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/Announce/integration/UpdateAnnounceTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/RestDocsConfig.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/admin/GetSignUpCouncilsTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/admin/UpdateRoleTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/auth/CheckEmailTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/auth/LoginCouncilTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/auth/LoginTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/auth/ReissueTokenTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/config/DatabaseCleaner.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/config/DatabaseClearExtension.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/council/SignUpCouncilTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/GetNoticeTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/notice/integration/UpdateNoticeTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationsTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/FindPasswordTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/LoginTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/user/UpdatePasswordTest.java
  Ticket-Common/build.gradle
  Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Password.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ErrorResponse.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/UnsupportedJwtException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/validator/PasswordValidator.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/AlreadyExistRegistrationException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/UserRole.java
Labels: 리팩터링, 테스트

#156 [BE-73] feat: 주차권 신청 기간 조회 조건 변경
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
  test-script/summary.json
Labels: 기능

#158 [BE-74] bug : 권한 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/docs/UpdateRoleExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/admin/service/AdminUseCase.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/admin/UpdateRoleTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/adaptor/AdminAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/AdminErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/AlreadyExistAdminException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/exception/NotAllowUpdateOwnRoleException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/admin/out/AdminRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/adaptor/UserAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/out/UserLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/repository/UserRepository.java
Labels: 버그

#167 [BE-81] style: 엑세스 토큰이 비어있는 경우 예외 메세지 수정
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Labels: 스타일

#168 [style] : GlobalErrorCode
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
Labels: 스타일
