Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2023-11, with the labels that each got.

#6 [BE-3] feat:Common Exception #4
  .gitignore
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/BadLockIdentifierException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/BaseErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ErrorReason.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ErrorResponse.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ExpiredTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidPasswordException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotAvailableRedissonLockException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerBadRequestException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerExpiredTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerForbiddenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerInternalSeverErrorException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerNotFoundException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerUnauthorizedException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OutOfIndexException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/RecruitCodeException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/RecruitDynamicException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/RefreshTokenExpiredException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/SecurityContextNotFoundException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/XssScriptAttackException.java
  build/spotless/spotlessJava/Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
  build/spotless/spotlessJava/Ticket-Api/src/test/java/com/jnu/ticketapi/TicketApiApplicationTests.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/TicketCommonApplication.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Adaptor.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/DateFormat.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/DevelopOnlyApi.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/DisableSwaggerSecurity.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/DomainService.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/EnumClass.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/ExceptionDoc.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Helper.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Port.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/UseCase.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Validator.java
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/XssProtected.java
  build/spotless/spotlessJava/Ticket-Common/src/test/java/com/jnu/ticketcommon/TicketCommonApplicationTests.java
  build/spotless/spotlessJava/Ticket-Domain/src/main/java/com/jnu/ticketdomain/TicketDomainApplication.java
  build/spotless/spotlessJava/Ticket-Domain/src/test/java/com/jnu/ticketdomain/TicketDomainApplicationTests.java
  build/spotless/spotlessJava/Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/TicketInfrastructureApplication.java
  build/spotless/spotlessJava/Ticket-Infrastructure/src/test/java/com/jnu/ticketinfrastructure/TicketInfrastructureApplicationTests.java
Labels: 기능, 문서화

#8 [BE-4] feat: GlobalExceptionHandler #7
  Ticket-Api/build/classes/java/main/com/jnu/ticketapi/TicketApiApplication.class
  Ticket-Api/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Api/src/main/java/com/jnu/ticketapi/TicketApiApplication.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/response/GlobalExceptionHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/response/SuccessResponseAdvice.java
  Ticket-Api/src/main/resources/application.properties
  Ticket-Api/src/main/resources/application.yml
  Ticket-Common/build/classes/java/main/com/jnu/ticketcommon/TicketCommonApplication.class
  Ticket-Common/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/TicketStatic.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/dto/SuccessResponse.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/BadLockIdentifierException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/ExpiredTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidPasswordException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InvalidTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/JsonSerializeFailedException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/NotAvailableRedissonLockException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerBadRequestException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerExpiredTokenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerForbiddenException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerInternalSeverErrorException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerNotFoundException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OtherServerUnauthorizedException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/OutOfIndexException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/RefreshTokenExpiredException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/SecurityContextNotFoundException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/TicketCodeException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/TicketDynamicException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/XssScriptAttackException.java
  Ticket-Domain/build/classes/java/main/com/jnu/ticketdomain/TicketDomainApplication.class
  Ticket-Domain/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/build/classes/java/main/com/jnu/ticketinfrastructure/TicketInfrastructureApplication.class
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
  build/spotless/spotlessJava/Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/ExplainError.java
Labels: 기능, 리팩터링

#10 [BE-5] feat: HttpContentCache처리 #9
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/HttpContentCacheFilter.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/ServletFilterConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebForwardedHeaderConfig.java
Labels: 기능

#19 [BE-9] feat: Redisson 분산락 설정 #17
  .gitignore
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/CallTransaction.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/CallTransactionFactory.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonCallNewTransaction.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonCallSameTransaction.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLock.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAop.java
  Ticket-Domain/src/main/resources/application.properties
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/CunCurrencyExecutorService.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/DisableDomainEvent.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/DisableRedissonLock.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/DomainIntegrateProfileResolver.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/DomainIntegrateSpringBootTest.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/DomainIntegrateTestConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisCacheConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedissonConfig.java
  Ticket-Infrastructure/src/main/resources/application-infrastructure.yml
  Ticket-Infrastructure/src/main/resources/application.properties
Labels: 기능

#26 [BE-10] [feat] : 시작/종료 설정 기능Structure
  Ticket-Api/src/main/java/com/jnu/ticketapi/adapter/in/SystemController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/port/ScheduleUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/service/ScheduleService.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleRequestDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ScheduleResponseDto.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/annotation/Port.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/System.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domain/system/SystemRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/out/SystemLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/out/SystemRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/persistence/SystemPersistenceAdapter.java
Labels: 기능

#35 [BE-17] feat: 1차신청 결과 메일링 서비스
  Ticket-Api/build.gradle
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/aws/AwsSesConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
  Ticket-Infrastructure/src/main/resources/application-infrastructure.yml
  Ticket-Infrastructure/src/main/resources/application.yml
Labels: 기능

#40 [BE-14] chore: jib와 Docker로 Github action을 통한 배포 파이프라인 추가
  .github/workflows/build.yaml
  .github/workflows/deploy.yaml
  .github/workflows/prod.yaml
  Ticket-Api/build.gradle
  Ticket-Api/build/classes/java/main/com/jnu/ticketapi/TicketApiApplication.class
  Ticket-Api/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Api/src/main/java/com/jnu/ticketapi/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/controller/UserController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/dto/ReissueTokenRequestDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/security/CustomUserDetails.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/test/java/com/jnu/ticketapi/TicketApiApplicationTests.java
  Ticket-Common/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Infrastructure/build/tmp/compileJava/previous-compilation-data.bin
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/aws/AwsSesConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
  build.gradle
  settings.gradle
Labels: 기능, 프로젝트 설정
