Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2024-02, with the labels that each got.

#237 [BE-113] feat: 이벤트의 PUBLISH 상태 변경 API
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/events/UpdatePublishStatusTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
Labels: 기능

#239 [BE-114] feat: 이벤트 PUBLISH 상태에 따라 시간/구간 설정 변경가능하게 로직 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/CreateEventExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorDeleteUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/PublishStatusTrueException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
Labels: 기능

#233 [BE-111] feat : 이벤트 생성 validation
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/CreateEventExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/request/EventRegisterRequest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java
Labels: 기능

#241 [BE-115] test: 실패한 테스트 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/test/java/com/jnu/ticketapi/admin/GetSignUpCouncilsTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/admin/UpdateRoleTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationsTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
Labels: 테스트

#244 [BE-117] feat : 이벤트 삭제
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/DeleteEventExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/test/java/com/jnu/ticketapi/events/DeleteEventTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
Labels: 기능

#248 [BE-118] refactor : 이벤트 PUBLISH 상태 변경
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/DeleteEventExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/docs/UpdatePublishStatusExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/request/UpdateEventPublishRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventRegisterUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/events/DeleteEventTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/events/UpdatePublishStatusTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/InternalSeverErrorException.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/utils/Result.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyExistPublishEventException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyPublishEventException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/AlreadyUnpublishEventException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/CannotPublishClosedEventException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
Labels: 리팩터링

#251 [BE-119] feat : 이벤트 목록 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java
Labels: 기능
