Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2024-09, with the labels that each got.

#351 [BE-170] feat: spring actuator thread pool endpoint 추가의 건
  Ticket-Api/src/main/java/com/jnu/ticketapi/common/actuator/ThreadPoolConfig.java
  Ticket-Api/src/main/resources/application.yml
Labels: 기능

#360 [BE-175] bug: redis 대기열에서 데이터를 pop 하고 db에 저장하지 못하는 문제
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/domainEvent/EventIssuedEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 버그

#362 [BE-176] refactor: ProcessQueueDataJob 리팩토링
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 리팩터링

#365 Refactor #177
  Ticket-Api/build.gradle
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/slack/sender/SlackInternalErrorSender.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/handler/UserReflectStatusEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationPublishEvent.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/User.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/UserStatus.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/domain/UserStatusConverter.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/user/event/UserReflectStatusEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 리팩터링, 버그

#375 [BE-181] bug: 임시저장 조회 오류
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 버그, 뜨거운 감자

#379 [BE-183] feat: 레디스 없이도 서버 정상 가동
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/controller/AuthController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/service/AuthUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
  Ticket-Common/build.gradle
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedissonConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/redissonLock/RedissonLockAop.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisRepository.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/redis/RedisService.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 기능

#381 [BE-184] feat: 서버 재시작시 유실된 스케줄러(job) 복구
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventCreationEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventUpdatedEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/AutoWiringSpringBeanJobFactory.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/ProcessQueueDataJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/QuartzConfig.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/config/QuartzJobLauncher.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java
  Ticket-Domain/src/main/resources/application-domain.yml
Labels: 기능

#387 [BE-186] bug: 이벤트 삭제가 되지 않는 오류
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventDeleteUseCase.java
Labels: 버그

#392 [BE-190] bug: 스케줄링 등록 안되는 버그
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java
Labels: 버그
