Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2024-04, with the labels that each got.

#283 [BE-135] bug: processEvent에서 registration이 null이뜨는 오류
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
Labels: 버그

#285 [BE-136] feat: 합불 메일 전송시 예비번호 상태 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/handler/RegistrationCreationEventHandler.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/mailService/MailServiceTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
Labels: 기능

#316 [BE-151] fix: DateTimePeriod format 변경
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/vo/DateTimePeriod.java
Labels: 버그

#321 [BE-153] bug: 임시저장하고 최종신청하면 신청이 두번 되는 오류
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/UpdatePublishStatusUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/CustomEventRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/CustomEventRepositoryImpl.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
Labels: 버그, 뜨거운 감자

#323 [BE-154] : style 예외 메세지 수정
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
Labels: 스타일
