Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2024-10, with the labels that each got.

#398 [BE-192] bug: Commons-pool2 의존성 제거
  Ticket-Common/build.gradle
Labels: 버그

#405 [BE-197] bug: ThreadPool 모니터링 개선
  Ticket-Api/src/main/java/com/jnu/ticketapi/common/actuator/ThreadPoolConfig.java
  Ticket-Api/src/main/resources/application.yml
Labels: 버그

#377 [BE-182] feat: jacoco, sonarcloud 도입의 건
  .github/workflows/code-covoerage.yaml
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/GetRegistrationsTest.java
  build.gradle
Labels: 기능

#406 [BE-195] bug: 캡차 암호화 일정한 문제 해결
  Ticket-Api/src/main/java/com/jnu/ticketapi/ConfigurationApiPropertiesConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/HashResult.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/EncryptionProperties.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomMockUser.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/WithCustomUserContextFactory.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCaseTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/application/helper/EncryptionTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/domain/CaptchaLog.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/WrongCaptchaCodeException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/out/CaptchaLogPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaLogRepository.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaLogRepositoryTest.java
Labels: 버그

#410 [BE-199] test: 인수 테스트용 PR
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
Labels: 테스트

#415 [BE-200] bug: redis 트랜잭션
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/redis/RedisConfig.java
Labels: 뜨거운 감자

#417 [BE-201] bug: redisson 의존성 삭제
  Ticket-Infrastructure/build.gradle
Labels: 뜨거운 감자
