Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2024-01, with the labels that each got.

#169 [BE-78] bug: 메일 전송시 신청 합격 상태가 전부 불합격으로 전송되는 버그 픽스
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
Labels: 버그

#170 [BE-76] docs : Valid 예외 docs
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/model/request/ReissueTokenRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/auth/ReissueTokenTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java
Labels: 문서화

#172 [BE-82] feat: 중복 최종 신청 방지 리펙토링 #171
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/resources/application-domain.yml
Labels: 기능

#176 [BE-85] feat: event timePeriod Validation off -> on
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CheckEmailExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/CouncilLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/auth/docs/UserLoginExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSignUpExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/EventWithDrawUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/FinalSaveExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/docs/TemporarySaveExceptionFDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLock.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/redissonLock/RedissonLockAop.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/NotOpenEventStatusException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/event/RegistrationCreationEvent.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java
Labels: 기능

#177 [BE-84] style: ValidationMessage 수정
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ValidationMessage.java
Labels: 스타일

#178 [BE-84] style : NOT_EVENT_OPEN_STATUS 메세지 수정
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
Labels: 스타일

#181 [ BE-87] bug: 구간 인원 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/response/SectorReadResponse.java
Labels: 버그, 뜨거운 감자

#182 [BE-87] bug : 구간 인원 설정
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
Labels: 버그

#186 [BE-88] feat: Sector 검증 기준 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/CreateSectorExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/model/request/SectorRegisterRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorDeleteUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/response/GlobalExceptionHandler.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/GlobalErrorCode.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/exception/MultiException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/event/EventTypeCheck.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/common/aop/event/EventTypeCheckAop.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/DuplicateSectorNameException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/InvalidSectorCapacityAndRemainException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/SectorErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationRecordPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
  Ticket-Domain/src/main/resources/application-domain.yml
  build.gradle
Labels: 기능, 리팩터링, 문서화

#194 [feat] : 이벤트 목록 조회 페이지네이션
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsPagingResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetEventsUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/EventAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/EventLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/EventRepository.java
Labels: 기능

#195 [BE-92] refactor: 신청 목록 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/controller/RegistrationController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 리팩터링

#198 [fix] : 이벤트 목록 조회 페이지네이션 버그 픽스
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
Labels: 버그

#201 [fix] : 이벤트 목록 조회 페이지네이션 날짜 포맷 변경
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventsInfoResponse.java
Labels: 리팩터링

#203 [BE-95] feat: 이벤트 상세 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/EventDetailResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetEventDetailUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
Labels: 기능

#207 [BE-99] bug: 1차 신청
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 버그, 뜨거운 감자

#209 [BE-99] : 1차 신청
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/exception/RegistrationErrorCode.java
Labels: 버그, 뜨거운 감자

#212 [ BE-101] bug: 1차 신청
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/out/RegistrationLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 버그, 뜨거운 감자

#215 [BE-103] bug: 구간 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
Labels: 버그, 뜨거운 감자

#220 [BE-105] feat: 만료된 Event 등록된 Registration (is_saved -> false) 배치처리 #219
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventCreationEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/EventUpdatedEventHandler.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchConfiguration.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/BatchQuartzJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/expired/SampleChunkListener.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventExpiration.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventRegisterJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/job/EventUpdateJob.java
  Ticket-Batch/src/main/java/com/jnu/ticketbatch/writer/RegistrationWriter.java
Labels: 기능, 뜨거운 감자

#222 [BE-106] bug: sectorNum 구간 이름 중복 검증 로직 수정 #221
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/UpdateSectorExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/InvalidSizeSectorException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/SectorErrorCode.java
Labels: 기능, 뜨거운 감자

#224 [BE-107] bug: sector post validation ( 기존 등록시 중복 방지 ) #223
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
Labels: 기능

#226 [BE-108][fix] :이벤트 상태에 따른 구간 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/controller/SectorController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorReadUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/out/SectorLoadPort.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
Labels: 뜨거운 감자

#227 [BE-108] [fix] :이벤트 상태에 따른 구간 조회
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Labels: 뜨거운 감자

#231 [BE-110] refactor: MultiException -> 단일 예외 롤백 #230
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/docs/UpdateSectorExceptionDocs.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/sector/service/SectorRegisterUseCase.java
  Ticket-Api/src/test/java/resources/application.yml
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/adaptor/SectorAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/repository/SectorRepository.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/resources/application-test.yml
Labels: 기능

#236 [BE-112] feat: 이벤트의 PUBLISH 상태 조회 API
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/model/response/PublishStatusResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/GetPublishStatusUseCase.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/config/BaseIntegrationTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/config/BaseUnitTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/events/GetPublishStatusTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Event.java
Labels: 기능
