Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2025-02, with the labels that each got.

#445 [BE-212, 213] bug: 테스트 에러 수정, Captcha 답변을 검증하도록 변경
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/SaveAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/UpdateAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessor.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/common/cache/EhcacheConfig.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessorTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/async/event_handler/user_reflect/ReflectUserTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaLogException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/AnnounceImage/config/TestDataSourceConfig.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/AnnounceImage/repository/AnnounceImageNativeRepositoryTest.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaLogRepositoryTest.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/EnableAsyncConfig.java
Labels: 버그

#449 개발서버 배포 테스트용 PR
  .github/workflows/build.yaml
  .github/workflows/dev-deploy-v2-container.yaml
  .github/workflows/dev.yaml
Labels: 테스트

#453 [BE-215] chore: DB 초기화 스크립트 최신화
  initdb/init.sql
Labels: 프로젝트 설정

#458 [BE-218] feat: fixed 환경에서 captcha 요청 및 답변 검증이 가능하도록 구현
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessor.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessor.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessorTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessorTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/FixedCaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/RandomCaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaRepositoryTest.java
Labels: 기능

#460 [BE-217] feat: 이메일 전송 기능 구현
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSendEmailException.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/handler/EmailSendEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/CouncilErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/SendFailEmailException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/event/SendEmailEvent.java
Labels: 기능

#464 [BE-221] feat: feat: 이메일 수동으로 보내는 api 에서 응답 값 설정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/response/SendEmailManuallyResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
Labels: 기능, 뜨거운 감자

#466 [BE-222] fix: 캡챠 답변 응답 메시지 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
Labels: 버그

#471 [BE-224] bug: 이메일 주소 환경변수에 의한 로컬 실행 및 테스트 에러 수정
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/CredentialCodeUseCase.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
Labels: 리팩터링, 버그
