Repository JNU-Parking-Ticket-Project/Parking-Ticket-BE, pull requests merged in 2025-03, with the labels that each got.

#473 [BE-225] 주차권 신청 정보에 소속 학과를 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/internal/RegistrationDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetRegistrationResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
Labels: 기능

#477 [BE-226] bug: 주차권 이벤트가 끝나지 않았을 때 이메일 전송 api 요청이 성공하는 오류
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/StillOpenEventException.java
Labels: 뜨거운 감자

#478 [BE-227] bug : 예비 번호 중복 문제 버그 임시 해결
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
Labels: 버그, 뜨거운 감자

#481 [25.03.09] 기능 추가 및 버그 수정
  .github/workflows/build.yaml
  .github/workflows/dev-deploy-v2-container.yaml
  .github/workflows/dev.yaml
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/SaveAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/announce/model/request/UpdateAnnounceRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessor.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessor.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/captcha/service/ValidateCaptchaUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/controller/CouncilController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/docs/CouncilSendEmailException.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/handler/EmailSendEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/model/response/SendEmailManuallyResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/council/service/CouncilUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/controller/EventController.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/handler/EventIssuedEventHandler.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/event/service/TestUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/user/service/CredentialCodeUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Encryption.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/common/cache/EhcacheConfig.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/config/WebConfig.java
  Ticket-Api/src/main/resources/application.yml
  Ticket-Api/src/main/resources/db/teardown.sql
  Ticket-Api/src/main/resources/templates/registration.html
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/FixedCaptchaHashProcessorTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/GetCaptchaUseCaseTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/api/captcha/service/RandomCaptchaHashProcessorTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/async/event_handler/user_reflect/ReflectUserTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/consts/MailTemplate.java
  Ticket-Common/src/main/java/com/jnu/ticketcommon/message/ResponseMessage.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/CaptchaLogAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/FixedCaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/adaptor/RandomCaptchaAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/CaptchaErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/exception/NotFoundCaptchaLogException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/captcha/repository/CaptchaRepository.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/CouncilErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/council/exception/SendFailEmailException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/domain/Sector.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/event/SendEmailEvent.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/EventErrorCode.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/events/exception/StillOpenEventException.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/adaptor/RegistrationAdaptor.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/repository/RegistrationRepository.java
  Ticket-Domain/src/main/resources/application-domain.yml
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/AnnounceImage/config/TestDataSourceConfig.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/AnnounceImage/repository/AnnounceImageNativeRepositoryTest.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaLogRepositoryTest.java
  Ticket-Domain/src/test/java/com/jnu/ticketdomain/domains/captcha/CaptchaRepositoryTest.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/config/EnableAsyncConfig.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/MailService.java
  initdb/init.sql
Labels: 기능, 버그, 프로젝트 설정

#482 [BE-225] 주차권 신청 정보에 소속 학과를 추가
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/internal/RegistrationDto.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/FinalSaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/request/TemporarySaveRequest.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/model/response/GetRegistrationResponse.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/api/registration/service/RegistrationUseCase.java
  Ticket-Api/src/main/java/com/jnu/ticketapi/application/helper/Converter.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveRequestTestDataBuilder.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/FinalSaveTest.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveRequestTestDataBuilder.java
  Ticket-Api/src/test/java/com/jnu/ticketapi/registration/TemporarySaveTest.java
  Ticket-Domain/src/main/java/com/jnu/ticketdomain/domains/registration/domain/Registration.java
  Ticket-Infrastructure/src/main/java/com/jnu/ticketinfrastructure/service/WaitingQueueService.java
Labels: 기능, 리팩터링, 테스트
